# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: WorkerPool
      demands: Agent.OSArchitecture -equals ARM64
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        containerRegistry: 'dockerhub_johanthedeveloper'
        repository: 'johanthedeveloper/azurepipelineagent'
        dockerfile: '$(Build.SourcesDirectory)/dockerfile'
        tags: |
          $(tag)
          latest

#        command: 'buildAndPush'
